<% if image.variant == 'alpine' -%>
FROM bcit/alpine:<%= image.labels['alpine_version'] %>
<% end -%>
<% if image.variant == 'centos' -%>
FROM bcit/centos:<%= image.labels['centos_version'] %>
<% end -%>
<%= snippet('labels', binding) -%>

ENV CATALINA_HOME /usr/local/tomcat
ENV PATH $CATALINA_HOME/bin:$PATH

WORKDIR $CATALINA_HOME

RUN mkdir -p /usr/local/tomcat \
 && chown 0:0 /usr/local/tomcat \
 && chmod 775 /usr/local/tomcat

ADD http://us.mirrors.quenda.co/apache/tomcat/tomcat-<%= image.version %>/v<%= image.labels['tomcat_version'] %>/bin/apache-tomcat-<%= image.labels['tomcat_version'] %>.tar.gz /usr/local/tomcat/

RUN tar zxf apache-tomcat-<%= image.labels['tomcat_version'] %>.tar.gz \
 && rm -f apache-tomcat-<%= image.labels['tomcat_version'] %>.tar.gz \
 && mv apache-tomcat-<%= image.labels['tomcat_version'] %>/* . \
 && rmdir apache-tomcat-<%= image.labels['tomcat_version'] %>

<% if image.variant == 'alpine' -%>
RUN apk add --no-cache \
      openjdk8 \
      tomcat-native
<% end -%>
<% if image.variant == 'centos' -%>
RUN rm -rf /var/cache/yum/* \
 && echo "exclude=mirror.layeronline.com" >> /etc/yum/pluginconf.d/fastestmirror.conf \
 && yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
      epel-release \
 && yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
      java-1.8.0-openjdk-devel \
      tomcat-native
<% end -%>

EXPOSE 8080
CMD ["catalina.sh", "run"]
